[project]
name = "socd"
version = "0.1.0"
description = "Library for simulating self-oscillating Class-D amplifiers"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "control>=0.10.1",
    "e2scapy",
    "matplotlib>=3.10.3",
    "numba>=0.60",
    "pymoo>=0.6.1.3",
    "symengine>=0.14.1",
    "sympy>=1.14.0",
]
[project.optional-dependencies]
cuda = [
    "nvmath-python[cu12,dx]>=0.3.0; sys_platform != 'darwin'",
    "numba-cuda>=0.11.0"
]

[tool.uv.sources]
e2scapy = { git = "https://gitlab.aaronlockhart.dev/aaronlockhartdev/e2-scapy" }
